Modify wave size to validate samples
ROCmSoftwarePlatform/rocWMMA pull request #111
Opened 2022-12-05 18:36 UTC by mkarunan

Updated wave size to reflect rocWMMA library
Verification successful on all supported architectures

2022-12-05 18:44 UTC, cgmillette requested changes
rocwmma::AMDGCN_WAVE_SIZE must only be used in __global__ or __device__ code.

Specifically with the launch parameters provided by the host, these need to be queried from the device (can use code from HipDevice.hpp)

2022-12-05 19:50 UTC, mkarunan commented
> rocwmma::AMDGCN_WAVE_SIZE must only be used in **global** or **device** code.
> 
> Specifically with the launch parameters provided by the host, these need to be queried from the device (can use code from HipDevice.hpp)

Host code has been updated with hip warp size and device/global code updated with rocwmma::AMDGCN_WAVE_SIZE.

2022-12-05 20:45 UTC, cgmillette commented on samples/hip_device.hpp
> +            std::cerr << "Cannot proceed: unsupported warp sizev detected. Exiting."
sizev

2022-12-05 20:46 UTC, cgmillette reviewed
Please put the device code in common.hpp to simply the sample code. Otherwise looks good!

2022-12-06 16:20 UTC, cgmillette approved these changes
LGTM

2022-12-06 16:23 UTC, merged