Sample GFX Arch Detection
ROCmSoftwarePlatform/rocWMMA pull request #254
Opened 2023-09-19 16:46 UTC by dlangbe

Detect the GFX architecture when running samples supported across multiple architectures.
- Default to using parameters beneficial to GFX11 on perf_hgemm
- Add wave and block size checks to perf_hgemm

2023-09-19 19:38 UTC, cgmillette commented on samples/common.hpp
> +        || (deviceName.find("gfx940") != std::string::npos));
Pls add gfx941, gfx942

2023-09-19 19:39 UTC, cgmillette commented on samples/common.hpp
> +    return (deviceName.find("gfx90a") != std::string::npos);
gfx940, gfx941, gfx942 will support f64

2023-09-19 19:44 UTC, cgmillette commented on samples/perf_hgemm.cpp
> +    gemm_cpu_h<InputT, OutputT, ComputeT, col_major, row_major, col_major>(m,
Can probably update the layouts to their aliases too

2023-09-19 20:00 UTC, cgmillette commented on samples/perf_hgemm.cpp
> +    if(isGfx11() && (ROCWMMA_M > 16 || ROCWMMA_N > 16))
Only block size supported is 16 x 16 for gfx11. Can possibly adjust to check
isGFX11() && ((ROCWMMA_M != ROCWMMA_N) || (ROCWMMA_M != 16))

Can do a similar check for gfx9 (16x16 and 32x32):
isGfx9() && ((ROCWMMA_M != ROCWMMA_N) || (ROCWMMA_M != 16 && ROCWMMA_M != 32))

2023-09-19 20:02 UTC, cgmillette commented on samples/perf_sgemm.cpp
Need to do similar checks as above, except sgemm isn't valid on gfx11.
    
    if(isGfx11() )
    {
        std::cout << "Unsupported architecture!\n";
        return;
    }
   ...
   // check block and wave size for gfx9... etc.
   ...

2023-09-19 20:05 UTC, cgmillette commented on samples/perf_dgemm.cpp
Similar to sgemm. check block / wave sizes for gfx90a, 941, 942

2023-09-19 20:12 UTC, cgmillette requested changes
Let's add gfx941 and gfx942 support.
When checking block and wave sizes, we should enforce sizes found in the support table. This is because in the sample we might expect that folks will tinker with configuration values.

These checks can be enforced for all samples to prevent possible false positives

2023-09-19 22:19 UTC, cgmillette approved these changes
Looks great, thanks!

2023-09-19 22:19 UTC, cgmillette commented
I'm going to restart the CI run. Had a failure on rocBLAS build earlier

2023-09-20 18:35 UTC, cgmillette commented
Please also duplicate this PR against release-staging/rocm-rel-6.0

2023-09-21 18:55 UTC, mkarunan approved these changes

2023-09-21 18:56 UTC, merged